package langlang

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

//go:embed zig/langlang_runtime.zig
var zigEvalContent embed.FS

// GenZigOptions configures the Zig backend.  The default output is one
// self-contained file with the runtime pasted in; RuntimeImport switches
// to `pub const runtime = @import("<RuntimeImport>");` for packages that
// host several parsers and vendor the runtime once.
type GenZigOptions struct {
	SourceFile    string
	RuntimeImport string
}

// zigRuntimeStdImport is the single line the emitter strips from the
// runtime file before pasting it inside the generated namespace (the
// generated file declares its own `std`).
const zigRuntimeStdImport = "const std = @import(\"std\");"

// zigRuntimeABIPattern finds the ABI number declared by the runtime so the
// emitted tables can carry it and the runtime can reject a mismatch at
// compile time.
var zigRuntimeABIPattern = regexp.MustCompile(`(?m)^pub const abi_version: u32 = (\d+);$`)

// zigCodeBytesPerLine keeps the bytecode literal readable and stable in
// diffs.
const zigCodeBytesPerLine = 24

// ZigRuntimeSource returns the embedded runtime, for `-zig-emit-runtime`
// and for tests.
func ZigRuntimeSource() []byte {
	data, err := zigEvalContent.ReadFile("zig/langlang_runtime.zig")
	if err != nil {
		panic(err.Error())
	}
	return data
}

// zigRuntimeABI reads the ABI version declared by the runtime source.
func zigRuntimeABI(runtime []byte) (string, error) {
	m := zigRuntimeABIPattern.FindSubmatch(runtime)
	if m == nil {
		return "", fmt.Errorf("zig runtime does not declare `pub const abi_version: u32 = N;`")
	}
	return string(m[1]), nil
}

// GenZigEval emits a Zig parser for the compiled grammar.  It shares the
// front end and `Encode` with GenGoEval, so the bytecode tables are the
// same bytes the Go backend carries; only the runtime differs.
func GenZigEval(asm *Program, cfg *Config, opt GenZigOptions) (string, error) {
	bt := Encode(asm, cfg)
	if err := checkZigTableLimits(bt); err != nil {
		return "", err
	}
	runtime := ZigRuntimeSource()
	abi, err := zigRuntimeABI(runtime)
	if err != nil {
		return "", err
	}
	g := &zigEvalEmitter{options: opt, out: newOutputWriter("    "), runtime: runtime, abi: abi}
	g.writePrelude()
	if err := g.writeRuntime(); err != nil {
		return "", err
	}
	g.writeTables(bt)
	g.writeRules(asm)
	g.writeParserAlias()
	g.writeTablesTest()
	return g.out.buffer.String(), nil
}

// checkZigTableLimits reports the cases the Go encoder truncates silently
// (`uint16(label)`): the VM addresses code and strings with u16 operands.
func checkZigTableLimits(bt *Bytecode) error {
	if len(bt.code) > 0xFFFF {
		return fmt.Errorf("zig backend: program is %d bytes, the bytecode ABI addresses at most 65535", len(bt.code))
	}
	if len(bt.strs) > 0xFFFF {
		return fmt.Errorf("zig backend: %d strings, the bytecode ABI addresses at most 65535", len(bt.strs))
	}
	if len(bt.sets) > 0xFFFF {
		return fmt.Errorf("zig backend: %d charsets, the bytecode ABI addresses at most 65535", len(bt.sets))
	}
	return nil
}

type zigEvalEmitter struct {
	options GenZigOptions
	out     *outputWriter
	runtime []byte
	abi     string
}

func (g *zigEvalEmitter) writePrelude() {
	sum := sha256.Sum256(g.runtime)
	g.out.writel(fmt.Sprintf("// Code generated by langlang (%s commit hash), DO NOT EDIT.", getCommitHash()))
	g.out.writel(fmt.Sprintf("// Source File: %s", g.options.SourceFile))
	g.out.writel(fmt.Sprintf("// Runtime: langlang_runtime.zig abi=%s sha256=%s (Zig 0.15.1, native + wasm32-freestanding, no libc)", g.abi, hex.EncodeToString(sum[:])))
	g.out.writel("const std = @import(\"std\");")
	g.out.writel("")
}

// writeRuntime pastes the runtime as a nested namespace.  The runtime's
// own `std` import is stripped; any other top-level import is an error so
// a runtime edit cannot silently produce a file that fails to compile.
// Nothing is re-exported from the namespace: a top-level `pub const Tree =
// runtime.Tree` would make every `Tree` inside the pasted runtime an
// ambiguous reference, so consumers spell `parser.runtime.Tree`.
func (g *zigEvalEmitter) writeRuntime() error {
	g.out.writel("// ---- BEGIN langlang runtime ----")
	if g.options.RuntimeImport != "" {
		g.out.writel(fmt.Sprintf("pub const runtime = @import(%s);", zigQuote(g.options.RuntimeImport)))
		g.out.writel("// ---- END langlang runtime ----")
		g.out.writel("")
		return nil
	}
	g.out.writel("pub const runtime = struct {")
	g.out.indent()
	stripped := 0
	lines := strings.Split(strings.TrimRight(string(g.runtime), "\n"), "\n")
	for _, line := range lines {
		if line == zigRuntimeStdImport {
			stripped++
			continue
		}
		if strings.HasPrefix(line, "const ") && strings.Contains(line, "@import(") {
			return fmt.Errorf("zig runtime has an extra top-level import (%q); only `%s` is allowed", line, zigRuntimeStdImport)
		}
		if line == "" {
			g.out.writel("")
			continue
		}
		g.out.writeil(line)
	}
	g.out.unindent()
	if stripped != 1 {
		return fmt.Errorf("zig runtime must contain exactly one `%s` line, found %d", zigRuntimeStdImport, stripped)
	}
	g.out.writel("};")
	g.out.writel("// ---- END langlang runtime ----")
	g.out.writel("")
	return nil
}

func (g *zigEvalEmitter) writeTables(bt *Bytecode) {
	g.out.writel("pub const bytecode = runtime.Bytecode{")
	g.out.indent()
	g.out.writeil(fmt.Sprintf(".abi = %s,", g.abi))

	// code
	g.out.writeil(".code = &[_]u8{")
	g.out.indent()
	g.writeAlignedRows(byteCells(bt.code))
	g.out.unindent()
	g.out.writeil("},")

	// strs
	g.out.writeil(".strs = &[_][]const u8{")
	g.out.indent()
	for _, s := range bt.strs {
		g.out.writeil(zigQuote(s) + ",")
	}
	g.out.unindent()
	g.out.writeil("},")

	// sets
	if len(bt.sets) == 0 {
		g.out.writeil(".sets = &.{},")
	} else {
		g.out.writeil(".sets = &[_]runtime.Charset{")
		g.out.indent()
		for _, set := range bt.sets {
			parts := make([]string, 0, len(set.bits))
			for _, b := range set.bits {
				parts = append(parts, fmt.Sprintf("%d", b))
			}
			g.out.writeil(fmt.Sprintf(".{ .bits = .{ %s } },", strings.Join(parts, ", ")))
		}
		g.out.unindent()
		g.out.writeil("},")
	}

	// sexp: one entry per charset, integers rather than rune literals
	if len(bt.sexp) == 0 {
		g.out.writeil(".sexp = &.{},")
	} else {
		g.out.writeil(".sexp = &[_][]const runtime.Expected{")
		g.out.indent()
		for _, item := range bt.sexp {
			if len(item) == 0 {
				g.out.writeil("&.{},")
				continue
			}
			parts := make([]string, 0, len(item))
			for _, sub := range item {
				if sub.b == 0 {
					parts = append(parts, fmt.Sprintf(".{ .a = %d }", sub.a))
				} else {
					parts = append(parts, fmt.Sprintf(".{ .a = %d, .b = %d }", sub.a, sub.b))
				}
			}
			if len(parts) == 1 {
				// zig fmt writes a one-element list of initializers without inner spaces.
				g.out.writeil(fmt.Sprintf("&.{%s},", parts[0]))
			} else {
				g.out.writeil(fmt.Sprintf("&.{ %s },", strings.Join(parts, ", ")))
			}
		}
		g.out.unindent()
		g.out.writeil("},")
	}

	// rxps: indexed by string id, -1 when the string is not a recovery label
	rxps := make([]string, 0, len(bt.strs))
	for id := range bt.strs {
		if addr, ok := bt.rxps[id]; ok {
			rxps = append(rxps, fmt.Sprintf("%d", addr))
		} else {
			rxps = append(rxps, "-1")
		}
	}
	g.out.writeil(".rxps = &[_]i32{")
	g.out.indent()
	g.writeAlignedRows(rxps)
	g.out.unindent()
	g.out.writeil("},")

	// srcm
	if bt.srcm == nil {
		g.out.writeil(".srcm = null,")
	} else {
		g.out.writeil(".srcm = &runtime.SourceMap{")
		g.out.indent()
		g.out.writeil(".data = &[_]u8{")
		g.out.indent()
		g.writeAlignedRows(byteCells(bt.srcm.Data))
		g.out.unindent()
		g.out.writeil("},")
		g.out.writeil(".files = &[_][]const u8{")
		g.out.indent()
		for _, f := range bt.srcm.Files {
			g.out.writeil(zigQuote(f) + ",")
		}
		g.out.unindent()
		g.out.writeil("},")
		g.out.unindent()
		g.out.writeil("},")
	}

	g.out.unindent()
	g.out.writel("};")
	g.out.writel("")
}

// writeRules emits the entry-address enum.  The address map is the same
// walk gen.go uses for the Go `Parse<Rule>` methods: every ILabel takes
// the byte cursor of the instruction that follows it.
func (g *zigEvalEmitter) writeRules(asm *Program) {
	var (
		cursor  = 0
		addrmap = make(map[int]int, len(asm.identifiers))
		labels  = make(map[int]int)
	)
	for i, instruction := range asm.code {
		switch ii := instruction.(type) {
		case ILabel:
			addrmap[i] = cursor
			labels[ii.ID] = cursor
		default:
			cursor += instruction.SizeInBytes()
		}
	}
	addrs := make([]int, 0, len(asm.identifiers))
	for addr := range asm.identifiers {
		addrs = append(addrs, addr)
	}
	sort.Ints(addrs)

	g.out.writel("pub const Rule = enum(u16) {")
	g.out.indent()
	for _, addr := range addrs {
		name := asm.strings[asm.identifiers[addr]]
		g.out.writeil(fmt.Sprintf("%s = %d,", zigIdent(name), addrmap[addr]))
	}
	g.out.unindent()
	g.out.writel("};")
	g.out.writel("")

	if len(addrs) > 0 {
		first := asm.strings[asm.identifiers[addrs[0]]]
		g.out.writel(fmt.Sprintf("pub const entry_rule: Rule = .%s;", zigIdent(first)))
	}

	// Rules entered through call_lr need an LR frame when a caller starts
	// a match at them directly.
	lrAddrs := map[int]bool{}
	for _, instruction := range asm.code {
		if ii, ok := instruction.(ICallLR); ok {
			lrAddrs[labels[ii.Label.ID]] = true
		}
	}
	lrNames := make([]string, 0, len(lrAddrs))
	for _, addr := range addrs {
		if lrAddrs[addrmap[addr]] {
			lrNames = append(lrNames, "."+zigIdent(asm.strings[asm.identifiers[addr]]))
		}
	}
	switch len(lrNames) {
	case 0:
		g.out.writel("pub const left_recursive_rules = [_]Rule{};")
	case 1:
		// zig fmt writes a one-element array literal without inner spaces.
		g.out.writel(fmt.Sprintf("pub const left_recursive_rules = [_]Rule{%s};", lrNames[0]))
	default:
		g.out.writel(fmt.Sprintf("pub const left_recursive_rules = [_]Rule{ %s };", strings.Join(lrNames, ", ")))
	}
	g.out.writel("")
}

func (g *zigEvalEmitter) writeParserAlias() {
	g.out.writel("pub const Parser = runtime.Parser(bytecode, Rule, &left_recursive_rules);")
	g.out.writel("")
}

func (g *zigEvalEmitter) writeTablesTest() {
	g.out.writel("test \"langlang tables\" {")
	g.out.indent()
	g.out.writeil("try runtime.verifyTables(bytecode);")
	g.out.unindent()
	g.out.writel("}")
}

// zigQuote renders s as a Zig string literal, escaping every byte that is
// not printable ASCII as \xNN so the literal round-trips arbitrary bytes.
func zigQuote(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString(`\"`)
		case c == '\\':
			b.WriteString(`\\`)
		case c == '\n':
			b.WriteString(`\n`)
		case c == '\r':
			b.WriteString(`\r`)
		case c == '\t':
			b.WriteString(`\t`)
		case c < 0x20 || c >= 0x7f:
			b.WriteString(fmt.Sprintf(`\x%02x`, c))
		default:
			b.WriteByte(c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// zigKeywords is the Zig 0.15.1 keyword set (std/zig/tokenizer.zig); a rule
// named after one must be spelled `@"name"`.
var zigKeywords = map[string]bool{
	"addrspace": true, "align": true, "allowzero": true, "and": true, "anyframe": true,
	"anytype": true, "asm": true, "break": true, "callconv": true, "catch": true,
	"comptime": true, "const": true, "continue": true, "defer": true, "else": true,
	"enum": true, "errdefer": true, "error": true, "export": true, "extern": true,
	"fn": true, "for": true, "if": true, "inline": true, "linksection": true,
	"noalias": true, "noinline": true, "nosuspend": true, "opaque": true, "or": true,
	"orelse": true, "packed": true, "pub": true, "resume": true, "return": true,
	"struct": true, "suspend": true, "switch": true, "test": true, "threadlocal": true,
	"try": true, "union": true, "unreachable": true, "var": true, "volatile": true,
	"while": true,
}

var zigPlainIdent = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// zigIdent renders a grammar name as a Zig identifier, quoting it as
// `@"..."` only when `zig fmt` would keep the quotes: names that are not
// plain identifiers and names that are keywords.  Quoting unconditionally
// would not survive `zig fmt`, which strips unnecessary `@"..."`.
func zigIdent(name string) string {
	if name == "_" || zigKeywords[name] || !zigPlainIdent.MatchString(name) {
		return "@" + zigQuote(name)
	}
	return name
}

func byteCells(data []byte) []string {
	cells := make([]string, 0, len(data))
	for _, b := range data {
		cells = append(cells, fmt.Sprintf("%d", b))
	}
	return cells
}

// writeAlignedRows emits cells zigCodeBytesPerLine per row, laid out the
// way `zig fmt` formats a multi-row array literal: every cell is followed
// by a comma and padded to the widest cell of its column, and rows end at
// their last comma.  Emitting it this way keeps the output `zig fmt`
// clean without running the formatter at generation time.
func (g *zigEvalEmitter) writeAlignedRows(cells []string) {
	if len(cells) == 0 {
		return
	}
	widths := make([]int, zigCodeBytesPerLine)
	for i, c := range cells {
		col := i % zigCodeBytesPerLine
		if len(c)+1 > widths[col] {
			widths[col] = len(c) + 1
		}
	}
	for i := 0; i < len(cells); i += zigCodeBytesPerLine {
		end := i + zigCodeBytesPerLine
		if end > len(cells) {
			end = len(cells)
		}
		var line strings.Builder
		for j := i; j < end; j++ {
			cell := cells[j] + ","
			line.WriteString(cell)
			if j+1 < end {
				line.WriteString(strings.Repeat(" ", widths[j-i]-len(cell)+1))
			}
		}
		g.out.writeil(line.String())
	}
}
